create table product_categories (
    id bigint generated by default as identity,
    name varchar(100) not null,
    description text,
    constraint pk_product_categories primary key (id)
);

create table products (
    id bigint generated by default as identity,
    category_id bigint not null,
    sku varchar(64) not null,
    title varchar(250) not null,
    description text,
    price numeric(12,2) not null,
    currency varchar(3) not null,
    product_type smallint not null check (product_type between 0 and 2),
    active boolean not null,
    constraint pk_products primary key (id),
    constraint uk_products_sku unique (sku),
    constraint fk_products_category
        foreign key (category_id)
        references product_categories (id)
);