services:
  kafka:
    image: apache/kafka:4.0.2
    container_name: shop-kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENERS: PLAINTEXT://:9092,CONTROLLER://:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@localhost:9093
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_LOG_DIRS: /var/lib/kafka/data
    volumes:
      - kafka-online-shop:/var/lib/kafka/data

  schema-registry:
    image: confluentinc/cp-schema-registry:8.0.5
    hostname: schema-registry
    container_name: schema-registry
    depends_on:
      - kafka
    ports:
      - 8081:8081
    environment:
      SCHEMA_REGISTRY_HOST_NAME: schema-registry
      SCHEMA_REGISTRY_LISTENERS: http://0.0.0.0:8081
      SCHEMA_REGISTRY_DEBUG: true
      SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS: PLAINTEXT://kafka:9092


  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: kafka-ui
    depends_on:
      - kafka
      - schema-registry
    ports:
      - "7777:8080"
    restart: always
    environment:
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:29092
      KAFKA_CLUSTERS_0_SCHEMAREGISTRY: http://schema-registry:8081
      KAFKA_CLUSTERS_0_NAME: kafka


  customerdb:
    profiles: ["customer"]
    image: postgres:16
    container_name: customerdb
    ports:
      - 5433:5432
    environment:
      POSTGRES_DB: customerdb
      POSTGRES_USER: shop
      POSTGRES_PASSWORD: shop
    volumes:
      - customerdb-data:/var/lib/postgresql/data

  productdb:
    profiles: ["product"]
    image: postgres:16
    container_name: productdb
    ports:
      - 5434:5432
    environment:
      POSTGRES_DB: productdb
      POSTGRES_USER: shop
      POSTGRES_PASSWORD: shop
    volumes:
      - productdb-data:/var/lib/postgresql/data

  orderdb:
    profiles: ["order"]
    image: postgres:16
    container_name: orderdb
    ports:
      - 5435:5432
    environment:
      POSTGRES_DB: orderdb
      POSTGRES_USER: shop
      POSTGRES_PASSWORD: shop
    volumes:
      - orderdb-data:/var/lib/postgresql/data

volumes:
  customerdb-data:
  orderdb-data:
  productdb-data:
  kafka-online-shop:
    driver: local

