spring:
  application:
    name: customer-service

  docker:
    compose:
      file: ../../compose.yaml
      lifecycle-management: start-only

  datasource:
    url: jdbc:postgresql://localhost:5433/customerdb
    username: shop
    password: shop

  flyway:
    enabled: true
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
        hbm2ddl:
          delimiter: ;

  kafka:
    bootstrap-servers: localhost:9092
