spring:
  application:
    name: delivery-service

  docker:
    compose:
      file: ../../compose.yaml
      lifecycle-management: start-only

#  datasource:
#    url: jdbc:postgresql://localhost:5439/deliverydb
#    username: shop
#    password: shop
#
#  flyway:
#    enabled: true
#  jpa:
#    hibernate:
#      ddl-auto: update
#    properties:
#      hibernate:
#        format_sql: true
#        hbm2ddl:
#          delimiter: ;


  kafka:
    bootstrap-servers: localhost:9092
