spring:
  application:
    name: payment-service

  docker:
    compose:
      file: ../../compose.yaml
      lifecycle-management: start-only

#  datasource:
#    url: jdbc:postgresql://localhost:5437/paymentdb
#    username: shop
#    password: shop
#  flyway:
#    enabled: true
#  jpa:
#    hibernate:
#      ddl-auto: validate
#    properties:
#      hibernate:
#        format_sql: true
#        hbm2ddl:
#          delimiter: ;

  kafka:
    bootstrap-servers: localhost:9092
