create table orders (
    id bigint generated by default as identity,
    order_id varchar(100) not null unique,
    customer_id bigint not null,
    status varchar(30) not null check (status in ('CANCELLED','CONFIRMED','CREATED','PAID')),
    total_amount numeric(12,2) not null,
    currency varchar(3) not null,
    constraint pk_orders primary key (id)
);

create table order_items (
    id bigint generated by default as identity,
    order_id bigint not null,
    product_id bigint not null,
    sku varchar(64) not null,
    title varchar(250) not null,
    quantity integer not null,
    unit_price numeric(12,2) not null,
    constraint pk_order_items primary key (id),
    constraint uk_order_items_order_sku unique (order_id, sku),
    constraint fk_order_items_order
        foreign key (order_id)
        references orders (id)
);