spring:
  application:
    name: order-service

  docker:
    compose:
      file: ../../compose.yaml
      lifecycle-management: start-only

  datasource:
    url: jdbc:postgresql://localhost:5435/orderdb
    username: shop
    password: shop

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        hbm2ddl:
          delimiter: ;
      jakarta:
        persistence:
          schema-generation:
            create-source: metadata
            scripts:
              action: create
              create-target: ./build/generated-ddl/orderdb-create.sql

  kafka:
    bootstrap-servers: localhost:9092
