spring:
  application:
    name: order-service

  docker:
    compose:
      file: ../../compose.yaml
      lifecycle-management: start-only

  datasource:
    url: jdbc:postgresql://localhost:5435/orderdb
    username: shop
    password: shop

  flyway:
    enabled: true
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: 'create-drop'  #validate
    properties:
      hibernate:
        format_sql: true
        hbm2ddl:
          delimiter: ;


  kafka:
    bootstrap-servers: localhost:9092
