spring:
  application:
    name: shopping-cart-service

  docker:
    compose:
      file: ../../compose.yaml
      lifecycle-management: start-only

#  datasource:
#    url: jdbc:postgresql://localhost:5435/cartdb
#    username: shop
#    password: shop
#
#  jpa:
#    hibernate:
#      ddl-auto: update
#    properties:
#      hibernate:
#        default_schema: cart
#    open-in-view: false

  kafka:
    bootstrap-servers: localhost:9092
