create table customers (
    id bigint generated by default as identity,
    given_name varchar(100) not null,
    family_name varchar(100) not null,
    date_of_birth date,
    gender varchar(20) check (gender in ('MALE','FEMALE','UNKNOWN')),
    primary key (id)
);

create table customer_contacts (
    id bigint generated by default as identity,
    customer_id bigint not null,
    category varchar(20) not null check (category in ('ADDRESS','PHONE','EMAIL')),
    contact_value varchar(500) not null,
    primary key (id)
);

alter table if exists customer_contacts
    add constraint fk_customer_contacts_customer
    foreign key (customer_id)
    references customers (id);